name: Flask CI

# ───── WHEN TO RUN ─────────────────────────────────────────────
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ───── WHAT TO DO ──────────────────────────────────────────────
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1) Get the code
      - uses: actions/checkout@v3

      # 2) Install Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          # if requirements.txt exists, install it; else just install Flask
          if [ -f requirements.txt ]; then
              pip install -r requirements.txt
          else
              pip install Flask
          fi

      # 4) Smoke‑test the app (import and start, then exit)
      - name: Run smoke test
        run: |
          python - <<'PY'
          import importlib, threading, time
          from flask import Flask

          # dynamically import your main module (assuming it's app.py)
          mod = importlib.import_module("app")
          app = getattr(mod, "app")

          # run Flask server in a thread for 3 sec to ensure it starts
          th = threading.Thread(target=app.run, kwargs=dict(port=5000))
          th.daemon = True
          th.start()
          time.sleep(3)
          print("Flask app started successfully.")
          PY
